import type { Metadata } from "next";
import localFont from "next/font/local";
import {georgia, workSans, poppins} from "./fonts/Fonts"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${georgia.variable} ${workSans.variable} ${poppins.variable} font-workSans`}
      >
        {children}
      </body>
    </html>
  );
}
